# This workflow will transer frontend repo build to the ec2 machine,
# the ec2 machine where build will be deploy is use to serve frontend for web application
# When there is a push to the "main" branch repo this workflow will run.
#
# In FRONTEND ec2 instance nginx and node js is pre-installed.

name: Deploy to production

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy-build-in-frontend-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" 
      - run: npm ci
      - run: npm run build

      - name: rsync deployments
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: build/
          remote_path: /var/www/html/
          remote_host: ec2-35-154-16-135.ap-south-1.compute.amazonaws.com
          remote_user: ubuntu
          remote_key: ${{ secrets.PRIVATE_KEY }}

    # Sets up SSH agent to allow SSH connections.
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

     # Runs SSH commands on the EC2 machine to deploy the Docker image.
      - name: Run SSH commands
        run: |
             sudo systemctl restart nginx
          
