name: Deploy to production

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" 
      - run: npm ci
      - run: npm run build

      - name: rsync deployments
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: build/
          remote_path: /var/www/html/
          remote_host: ec2-35-154-16-135.ap-south-1.compute.amazonaws.com
          remote_user: ubuntu
          remote_key: ${{ secrets.PRIVATE_KEY }}

      - name: multiple command
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ec2-35-154-16-135.ap-south-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            sudo systemctl restart nginx

          
